"use client";

import DocsToc from "@/components/DocsToc";

const TOC = [
  { id: "t-ai", label: "AI-generated content" },
  { id: "t-acc", label: "No guarantee of accuracy" },
  { id: "t-api", label: "API usage" },
  { id: "t-indep", label: "Independent project" },
];

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-5 py-10 flex-1 w-full">
      <div className="docs-shell">
        <DocsToc items={TOC} />

        <main className="min-w-0">
          <div className="mono text-[11px] tracking-wide uppercase text-[#3ecb63] font-semibold mb-2">Terms of Use · Updated July 2026</div>
          <h1 className="text-2xl font-bold font-display mb-2">Read the heatmap. Make your own call.</h1>
          <p className="text-gray-500 mb-8">
            Observo shows patterns in public on-chain data and AI commentary about those patterns —
            nothing more.
          </p>

          <div className="callout mb-8">
            <span className="k">Not financial advice</span>
            <p className="text-[14.5px] text-gray-300">
              Scores, verdicts, reasoning, and heatmap colors are not financial, investment, or
              trading advice. Crypto markets are volatile and past patterns don&apos;t guarantee
              future results. You are solely responsible for your own decisions.
            </p>
          </div>

          <h2 id="t-ai" className="font-semibold font-display text-lg mt-11 mb-3 scroll-mt-24">AI-generated content</h2>
          <p className="text-sm text-gray-400 leading-relaxed">
            Verdicts and reasoning shown on Observo are generated by an AI system based on on-chain
            data. While we design the system to avoid guessing when data is insufficient, AI outputs
            can be wrong, incomplete, or miss context a human would catch. Use your own judgment.
          </p>

          <h2 id="t-acc" className="font-semibold font-display text-lg mt-11 mb-3 scroll-mt-24">No guarantee of accuracy</h2>
          <p className="text-sm text-gray-400 leading-relaxed">
            We aggregate data from public blockchain sources and third-party APIs. We do our best to
            keep this accurate and up to date, but we don&apos;t guarantee completeness, accuracy, or
            availability of the service at all times.
          </p>

          <h2 id="t-api" className="font-semibold font-display text-lg mt-11 mb-3 scroll-mt-24">API usage</h2>
          <p className="text-sm text-gray-400 leading-relaxed">
            The Observo API is provided for building tools, bots, and agents on top of our data. Please
            don&apos;t abuse rate limits or resell raw access without permission. We may throttle or suspend
            access that disrupts the service for others.
          </p>

          <h2 id="t-indep" className="font-semibold font-display text-lg mt-11 mb-3 scroll-mt-24">Independent project</h2>
          <p className="text-sm text-gray-400 leading-relaxed">
            Observo is an independent, community-built tool. It is not affiliated with, endorsed by, or
            operated by Robinhood, Pons, flap.sh, or bow.fun.
          </p>
        </main>
      </div>
    </div>
  );
}
