export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-5 py-10 flex-1 w-full">
      <h1 className="text-2xl font-bold mb-2">Terms of Use</h1>
      <p className="text-gray-500 mb-8 text-sm">Last updated: July 2026</p>

      <div className="card p-6 mb-5">
        <h2 className="font-semibold mb-2">Not financial advice</h2>
        <p className="text-sm text-gray-600 leading-relaxed">
          Observo shows patterns in public on-chain data and AI-generated commentary about those
          patterns. Nothing on Observo — scores, verdicts, reasoning, or heatmap colors — is financial,
          investment, or trading advice. Crypto markets are volatile and past patterns don&apos;t guarantee
          future results. You are solely responsible for your own decisions.
        </p>
      </div>

      <div className="card p-6 mb-5">
        <h2 className="font-semibold mb-2">AI-generated content</h2>
        <p className="text-sm text-gray-600 leading-relaxed">
          Verdicts and reasoning shown on Observo are generated by an AI system based on on-chain
          data. While we design the system to avoid guessing when data is insufficient, AI outputs
          can be wrong, incomplete, or miss context a human would catch. Use your own judgment.
        </p>
      </div>

      <div className="card p-6 mb-5">
        <h2 className="font-semibold mb-2">No guarantee of accuracy</h2>
        <p className="text-sm text-gray-600 leading-relaxed">
          We aggregate data from public blockchain sources and third-party APIs. We do our best to
          keep this accurate and up to date, but we don&apos;t guarantee completeness, accuracy, or
          availability of the service at all times.
        </p>
      </div>

      <div className="card p-6 mb-5">
        <h2 className="font-semibold mb-2">API usage</h2>
        <p className="text-sm text-gray-600 leading-relaxed">
          The Observo API is provided for building tools, bots, and agents on top of our data. Please
          don&apos;t abuse rate limits or resell raw access without permission. We may throttle or suspend
          access that disrupts the service for others.
        </p>
      </div>

      <div className="card p-6">
        <h2 className="font-semibold mb-2">Independent project</h2>
        <p className="text-sm text-gray-600 leading-relaxed">
          Observo is an independent, community-built tool. It is not affiliated with, endorsed by, or
          operated by Robinhood, Pons, flap.sh, or bow.fun.
        </p>
      </div>
    </div>
  );
}
